/// Flutter icons SmartHummusIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SmartHummusIcons
///      fonts:
///       - asset: fonts/SmartHummusIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SmartHummusIcons {
  SmartHummusIcons._();

  static const _kFontFam = 'SmartHummusIcons';
  static const _kFontPkg = null;

  static const IconData home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pig = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gas = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData composter = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData problem = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alright = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
